[package]
name = "nspt_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
nspt_common = { path = "../nspt_common" }
rand = "0.8.5"
